version: '3.7'

services:
    traefik:
        image: traefik:v2.1.4
        command: 
            - --log.level=INFO
            - --log.filePath=/mnt/traefik.log
            - --accesslog=true
            - --accesslog.filepath=/mnt/access.log
            - --entrypoints.web.address=:80
            - --api
            - --providers.docker=true
            - --providers.docker.exposedByDefault=false
            - --providers.docker.network=testnet
        ports: 
            - "80:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./log:/mnt
        networks:
            default:
            testnet:
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.traefik.rule=Host(`subdomain.domain.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
            - "traefik.http.routers.traefik.service=api@internal"
            - "traefik.http.routers.traefik.middlewares=auth"
            - "traefik.http.middlewares.auth.basicauth.users=traefik:$$apr1$$KOtOhxDu$$3NIK.pwi8Pzq2Nhw7USG30"

networks:
    default:
    testnet:
        internal: true